[package]
name = "faucet"
version = "0.2.7"

[dependencies]
AptosFramework = { local = '../aptos-core/aptos-move/framework/aptos-framework' }
TestCoins = { local = "../test-coins" }

[addresses]
account = '_'
test_coins = "_"
