[package]
name = "faucet"
version = "0.2.7"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "971c160079263a8d3e1d2503a570b01ecaaf10ba"
subdir = "aptos-move/framework/aptos-framework/"

[addresses]
account = "_"
